CREATE TABLE users (
	id UUID,
	email VARCHAR(255) NOT NULL,
	first_name VARCHAR(255) NOT NULL,
	last_name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	deleted_at TIMESTAMP DEFAULT NULL,
	archived_at TIMESTAMP DEFAULT NULL,
	PRIMARY KEY (id)
);
