CREATE TABLE companies (
	id UUID,
	name VARCHAR(255) NOT NULL,
	logo_url VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	deleted_at TIMESTAMP DEFAULT NULL,
	archived_at TIMESTAMP DEFAULT NULL,
	PRIMARY KEY (id)
);
