// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BlockCategory is the predicate function for blockcategory builders.
type BlockCategory func(*sql.Selector)

// BlockInfo is the predicate function for blockinfo builders.
type BlockInfo func(*sql.Selector)

// Bot is the predicate function for bot builders.
type Bot func(*sql.Selector)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
