linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - depguard
    - gci
    - wrapcheck
    - varnamelen
severity:
  default-severity: warning
