// Code generated by ent, DO NOT EDIT.

package blockcategory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the blockcategory type in the database.
	Label = "block_category"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldArchivedAt holds the string denoting the archived_at field in the database.
	FieldArchivedAt = "archived_at"
	// EdgeBlocks holds the string denoting the blocks edge name in mutations.
	EdgeBlocks = "blocks"
	// EdgeBot holds the string denoting the bot edge name in mutations.
	EdgeBot = "bot"
	// Table holds the table name of the blockcategory in the database.
	Table = "block_categories"
	// BlocksTable is the table that holds the blocks relation/edge.
	BlocksTable = "block_infos"
	// BlocksInverseTable is the table name for the BlockInfo entity.
	// It exists in this package in order to avoid circular dependency with the "blockinfo" package.
	BlocksInverseTable = "block_infos"
	// BlocksColumn is the table column denoting the blocks relation/edge.
	BlocksColumn = "block_category_blocks"
	// BotTable is the table that holds the bot relation/edge.
	BotTable = "block_categories"
	// BotInverseTable is the table name for the Bot entity.
	// It exists in this package in order to avoid circular dependency with the "bot" package.
	BotInverseTable = "bots"
	// BotColumn is the table column denoting the bot relation/edge.
	BotColumn = "bot_blocks"
)

// Columns holds all SQL columns for blockcategory fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldArchivedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "block_categories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"bot_blocks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the BlockCategory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByArchivedAt orders the results by the archived_at field.
func ByArchivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchivedAt, opts...).ToFunc()
}

// ByBlocksCount orders the results by blocks count.
func ByBlocksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBlocksStep(), opts...)
	}
}

// ByBlocks orders the results by blocks terms.
func ByBlocks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBlocksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBotField orders the results by bot field.
func ByBotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBotStep(), sql.OrderByField(field, opts...))
	}
}
func newBlocksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BlocksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BlocksTable, BlocksColumn),
	)
}
func newBotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BotTable, BotColumn),
	)
}
