// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"oliapi/ent/blockcategory"
	"oliapi/ent/blockinfo"
	"oliapi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BlockInfoQuery is the builder for querying BlockInfo entities.
type BlockInfoQuery struct {
	config
	ctx          *QueryContext
	order        []blockinfo.OrderOption
	inters       []Interceptor
	predicates   []predicate.BlockInfo
	withCategory *BlockCategoryQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlockInfoQuery builder.
func (biq *BlockInfoQuery) Where(ps ...predicate.BlockInfo) *BlockInfoQuery {
	biq.predicates = append(biq.predicates, ps...)
	return biq
}

// Limit the number of records to be returned by this query.
func (biq *BlockInfoQuery) Limit(limit int) *BlockInfoQuery {
	biq.ctx.Limit = &limit
	return biq
}

// Offset to start from.
func (biq *BlockInfoQuery) Offset(offset int) *BlockInfoQuery {
	biq.ctx.Offset = &offset
	return biq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (biq *BlockInfoQuery) Unique(unique bool) *BlockInfoQuery {
	biq.ctx.Unique = &unique
	return biq
}

// Order specifies how the records should be ordered.
func (biq *BlockInfoQuery) Order(o ...blockinfo.OrderOption) *BlockInfoQuery {
	biq.order = append(biq.order, o...)
	return biq
}

// QueryCategory chains the current query on the "category" edge.
func (biq *BlockInfoQuery) QueryCategory() *BlockCategoryQuery {
	query := (&BlockCategoryClient{config: biq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := biq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := biq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blockinfo.Table, blockinfo.FieldID, selector),
			sqlgraph.To(blockcategory.Table, blockcategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blockinfo.CategoryTable, blockinfo.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(biq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BlockInfo entity from the query.
// Returns a *NotFoundError when no BlockInfo was found.
func (biq *BlockInfoQuery) First(ctx context.Context) (*BlockInfo, error) {
	nodes, err := biq.Limit(1).All(setContextOp(ctx, biq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blockinfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (biq *BlockInfoQuery) FirstX(ctx context.Context) *BlockInfo {
	node, err := biq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlockInfo ID from the query.
// Returns a *NotFoundError when no BlockInfo ID was found.
func (biq *BlockInfoQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = biq.Limit(1).IDs(setContextOp(ctx, biq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blockinfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (biq *BlockInfoQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := biq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlockInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlockInfo entity is found.
// Returns a *NotFoundError when no BlockInfo entities are found.
func (biq *BlockInfoQuery) Only(ctx context.Context) (*BlockInfo, error) {
	nodes, err := biq.Limit(2).All(setContextOp(ctx, biq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blockinfo.Label}
	default:
		return nil, &NotSingularError{blockinfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (biq *BlockInfoQuery) OnlyX(ctx context.Context) *BlockInfo {
	node, err := biq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlockInfo ID in the query.
// Returns a *NotSingularError when more than one BlockInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (biq *BlockInfoQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = biq.Limit(2).IDs(setContextOp(ctx, biq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blockinfo.Label}
	default:
		err = &NotSingularError{blockinfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (biq *BlockInfoQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := biq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlockInfos.
func (biq *BlockInfoQuery) All(ctx context.Context) ([]*BlockInfo, error) {
	ctx = setContextOp(ctx, biq.ctx, "All")
	if err := biq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlockInfo, *BlockInfoQuery]()
	return withInterceptors[[]*BlockInfo](ctx, biq, qr, biq.inters)
}

// AllX is like All, but panics if an error occurs.
func (biq *BlockInfoQuery) AllX(ctx context.Context) []*BlockInfo {
	nodes, err := biq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlockInfo IDs.
func (biq *BlockInfoQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if biq.ctx.Unique == nil && biq.path != nil {
		biq.Unique(true)
	}
	ctx = setContextOp(ctx, biq.ctx, "IDs")
	if err = biq.Select(blockinfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (biq *BlockInfoQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := biq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (biq *BlockInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, biq.ctx, "Count")
	if err := biq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, biq, querierCount[*BlockInfoQuery](), biq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (biq *BlockInfoQuery) CountX(ctx context.Context) int {
	count, err := biq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (biq *BlockInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, biq.ctx, "Exist")
	switch _, err := biq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (biq *BlockInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := biq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlockInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (biq *BlockInfoQuery) Clone() *BlockInfoQuery {
	if biq == nil {
		return nil
	}
	return &BlockInfoQuery{
		config:       biq.config,
		ctx:          biq.ctx.Clone(),
		order:        append([]blockinfo.OrderOption{}, biq.order...),
		inters:       append([]Interceptor{}, biq.inters...),
		predicates:   append([]predicate.BlockInfo{}, biq.predicates...),
		withCategory: biq.withCategory.Clone(),
		// clone intermediate query.
		sql:  biq.sql.Clone(),
		path: biq.path,
	}
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (biq *BlockInfoQuery) WithCategory(opts ...func(*BlockCategoryQuery)) *BlockInfoQuery {
	query := (&BlockCategoryClient{config: biq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	biq.withCategory = query
	return biq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlockInfo.Query().
//		GroupBy(blockinfo.FieldContent).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (biq *BlockInfoQuery) GroupBy(field string, fields ...string) *BlockInfoGroupBy {
	biq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlockInfoGroupBy{build: biq}
	grbuild.flds = &biq.ctx.Fields
	grbuild.label = blockinfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Content string `json:"content,omitempty"`
//	}
//
//	client.BlockInfo.Query().
//		Select(blockinfo.FieldContent).
//		Scan(ctx, &v)
func (biq *BlockInfoQuery) Select(fields ...string) *BlockInfoSelect {
	biq.ctx.Fields = append(biq.ctx.Fields, fields...)
	sbuild := &BlockInfoSelect{BlockInfoQuery: biq}
	sbuild.label = blockinfo.Label
	sbuild.flds, sbuild.scan = &biq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlockInfoSelect configured with the given aggregations.
func (biq *BlockInfoQuery) Aggregate(fns ...AggregateFunc) *BlockInfoSelect {
	return biq.Select().Aggregate(fns...)
}

func (biq *BlockInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range biq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, biq); err != nil {
				return err
			}
		}
	}
	for _, f := range biq.ctx.Fields {
		if !blockinfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if biq.path != nil {
		prev, err := biq.path(ctx)
		if err != nil {
			return err
		}
		biq.sql = prev
	}
	return nil
}

func (biq *BlockInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlockInfo, error) {
	var (
		nodes       = []*BlockInfo{}
		withFKs     = biq.withFKs
		_spec       = biq.querySpec()
		loadedTypes = [1]bool{
			biq.withCategory != nil,
		}
	)
	if biq.withCategory != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blockinfo.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlockInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlockInfo{config: biq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, biq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := biq.withCategory; query != nil {
		if err := biq.loadCategory(ctx, query, nodes, nil,
			func(n *BlockInfo, e *BlockCategory) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (biq *BlockInfoQuery) loadCategory(ctx context.Context, query *BlockCategoryQuery, nodes []*BlockInfo, init func(*BlockInfo), assign func(*BlockInfo, *BlockCategory)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlockInfo)
	for i := range nodes {
		if nodes[i].block_category_blocks == nil {
			continue
		}
		fk := *nodes[i].block_category_blocks
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(blockcategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "block_category_blocks" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (biq *BlockInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := biq.querySpec()
	_spec.Node.Columns = biq.ctx.Fields
	if len(biq.ctx.Fields) > 0 {
		_spec.Unique = biq.ctx.Unique != nil && *biq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, biq.driver, _spec)
}

func (biq *BlockInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blockinfo.Table, blockinfo.Columns, sqlgraph.NewFieldSpec(blockinfo.FieldID, field.TypeUUID))
	_spec.From = biq.sql
	if unique := biq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if biq.path != nil {
		_spec.Unique = true
	}
	if fields := biq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blockinfo.FieldID)
		for i := range fields {
			if fields[i] != blockinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := biq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := biq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := biq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := biq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (biq *BlockInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(biq.driver.Dialect())
	t1 := builder.Table(blockinfo.Table)
	columns := biq.ctx.Fields
	if len(columns) == 0 {
		columns = blockinfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if biq.sql != nil {
		selector = biq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if biq.ctx.Unique != nil && *biq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range biq.predicates {
		p(selector)
	}
	for _, p := range biq.order {
		p(selector)
	}
	if offset := biq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := biq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlockInfoGroupBy is the group-by builder for BlockInfo entities.
type BlockInfoGroupBy struct {
	selector
	build *BlockInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bigb *BlockInfoGroupBy) Aggregate(fns ...AggregateFunc) *BlockInfoGroupBy {
	bigb.fns = append(bigb.fns, fns...)
	return bigb
}

// Scan applies the selector query and scans the result into the given value.
func (bigb *BlockInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bigb.build.ctx, "GroupBy")
	if err := bigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockInfoQuery, *BlockInfoGroupBy](ctx, bigb.build, bigb, bigb.build.inters, v)
}

func (bigb *BlockInfoGroupBy) sqlScan(ctx context.Context, root *BlockInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bigb.fns))
	for _, fn := range bigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bigb.flds)+len(bigb.fns))
		for _, f := range *bigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlockInfoSelect is the builder for selecting fields of BlockInfo entities.
type BlockInfoSelect struct {
	*BlockInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bis *BlockInfoSelect) Aggregate(fns ...AggregateFunc) *BlockInfoSelect {
	bis.fns = append(bis.fns, fns...)
	return bis
}

// Scan applies the selector query and scans the result into the given value.
func (bis *BlockInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bis.ctx, "Select")
	if err := bis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockInfoQuery, *BlockInfoSelect](ctx, bis.BlockInfoQuery, bis, bis.inters, v)
}

func (bis *BlockInfoSelect) sqlScan(ctx context.Context, root *BlockInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bis.fns))
	for _, fn := range bis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
