// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"oliapi/ent/blockcategory"
	"oliapi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlockCategoryDelete is the builder for deleting a BlockCategory entity.
type BlockCategoryDelete struct {
	config
	hooks    []Hook
	mutation *BlockCategoryMutation
}

// Where appends a list predicates to the BlockCategoryDelete builder.
func (bcd *BlockCategoryDelete) Where(ps ...predicate.BlockCategory) *BlockCategoryDelete {
	bcd.mutation.Where(ps...)
	return bcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bcd *BlockCategoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bcd.sqlExec, bcd.mutation, bcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bcd *BlockCategoryDelete) ExecX(ctx context.Context) int {
	n, err := bcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bcd *BlockCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(blockcategory.Table, sqlgraph.NewFieldSpec(blockcategory.FieldID, field.TypeUUID))
	if ps := bcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bcd.mutation.done = true
	return affected, err
}

// BlockCategoryDeleteOne is the builder for deleting a single BlockCategory entity.
type BlockCategoryDeleteOne struct {
	bcd *BlockCategoryDelete
}

// Where appends a list predicates to the BlockCategoryDelete builder.
func (bcdo *BlockCategoryDeleteOne) Where(ps ...predicate.BlockCategory) *BlockCategoryDeleteOne {
	bcdo.bcd.mutation.Where(ps...)
	return bcdo
}

// Exec executes the deletion query.
func (bcdo *BlockCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := bcdo.bcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{blockcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bcdo *BlockCategoryDeleteOne) ExecX(ctx context.Context) {
	if err := bcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
