// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"oliapi/ent/blockinfo"
	"oliapi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlockInfoDelete is the builder for deleting a BlockInfo entity.
type BlockInfoDelete struct {
	config
	hooks    []Hook
	mutation *BlockInfoMutation
}

// Where appends a list predicates to the BlockInfoDelete builder.
func (bid *BlockInfoDelete) Where(ps ...predicate.BlockInfo) *BlockInfoDelete {
	bid.mutation.Where(ps...)
	return bid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bid *BlockInfoDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, bid.sqlExec, bid.mutation, bid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (bid *BlockInfoDelete) ExecX(ctx context.Context) int {
	n, err := bid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bid *BlockInfoDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(blockinfo.Table, sqlgraph.NewFieldSpec(blockinfo.FieldID, field.TypeUUID))
	if ps := bid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, bid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	bid.mutation.done = true
	return affected, err
}

// BlockInfoDeleteOne is the builder for deleting a single BlockInfo entity.
type BlockInfoDeleteOne struct {
	bid *BlockInfoDelete
}

// Where appends a list predicates to the BlockInfoDelete builder.
func (bido *BlockInfoDeleteOne) Where(ps ...predicate.BlockInfo) *BlockInfoDeleteOne {
	bido.bid.mutation.Where(ps...)
	return bido
}

// Exec executes the deletion query.
func (bido *BlockInfoDeleteOne) Exec(ctx context.Context) error {
	n, err := bido.bid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{blockinfo.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bido *BlockInfoDeleteOne) ExecX(ctx context.Context) {
	if err := bido.Exec(ctx); err != nil {
		panic(err)
	}
}
