// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"oliapi/ent/blockcategory"
	"oliapi/ent/blockinfo"
	"oliapi/ent/bot"
	"oliapi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BlockCategoryQuery is the builder for querying BlockCategory entities.
type BlockCategoryQuery struct {
	config
	ctx        *QueryContext
	order      []blockcategory.OrderOption
	inters     []Interceptor
	predicates []predicate.BlockCategory
	withBlocks *BlockInfoQuery
	withBot    *BotQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlockCategoryQuery builder.
func (bcq *BlockCategoryQuery) Where(ps ...predicate.BlockCategory) *BlockCategoryQuery {
	bcq.predicates = append(bcq.predicates, ps...)
	return bcq
}

// Limit the number of records to be returned by this query.
func (bcq *BlockCategoryQuery) Limit(limit int) *BlockCategoryQuery {
	bcq.ctx.Limit = &limit
	return bcq
}

// Offset to start from.
func (bcq *BlockCategoryQuery) Offset(offset int) *BlockCategoryQuery {
	bcq.ctx.Offset = &offset
	return bcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bcq *BlockCategoryQuery) Unique(unique bool) *BlockCategoryQuery {
	bcq.ctx.Unique = &unique
	return bcq
}

// Order specifies how the records should be ordered.
func (bcq *BlockCategoryQuery) Order(o ...blockcategory.OrderOption) *BlockCategoryQuery {
	bcq.order = append(bcq.order, o...)
	return bcq
}

// QueryBlocks chains the current query on the "blocks" edge.
func (bcq *BlockCategoryQuery) QueryBlocks() *BlockInfoQuery {
	query := (&BlockInfoClient{config: bcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blockcategory.Table, blockcategory.FieldID, selector),
			sqlgraph.To(blockinfo.Table, blockinfo.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, blockcategory.BlocksTable, blockcategory.BlocksColumn),
		)
		fromU = sqlgraph.SetNeighbors(bcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBot chains the current query on the "bot" edge.
func (bcq *BlockCategoryQuery) QueryBot() *BotQuery {
	query := (&BotClient{config: bcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(blockcategory.Table, blockcategory.FieldID, selector),
			sqlgraph.To(bot.Table, bot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, blockcategory.BotTable, blockcategory.BotColumn),
		)
		fromU = sqlgraph.SetNeighbors(bcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first BlockCategory entity from the query.
// Returns a *NotFoundError when no BlockCategory was found.
func (bcq *BlockCategoryQuery) First(ctx context.Context) (*BlockCategory, error) {
	nodes, err := bcq.Limit(1).All(setContextOp(ctx, bcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{blockcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bcq *BlockCategoryQuery) FirstX(ctx context.Context) *BlockCategory {
	node, err := bcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlockCategory ID from the query.
// Returns a *NotFoundError when no BlockCategory ID was found.
func (bcq *BlockCategoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bcq.Limit(1).IDs(setContextOp(ctx, bcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{blockcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bcq *BlockCategoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := bcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlockCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlockCategory entity is found.
// Returns a *NotFoundError when no BlockCategory entities are found.
func (bcq *BlockCategoryQuery) Only(ctx context.Context) (*BlockCategory, error) {
	nodes, err := bcq.Limit(2).All(setContextOp(ctx, bcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{blockcategory.Label}
	default:
		return nil, &NotSingularError{blockcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bcq *BlockCategoryQuery) OnlyX(ctx context.Context) *BlockCategory {
	node, err := bcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlockCategory ID in the query.
// Returns a *NotSingularError when more than one BlockCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (bcq *BlockCategoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bcq.Limit(2).IDs(setContextOp(ctx, bcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{blockcategory.Label}
	default:
		err = &NotSingularError{blockcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bcq *BlockCategoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := bcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlockCategories.
func (bcq *BlockCategoryQuery) All(ctx context.Context) ([]*BlockCategory, error) {
	ctx = setContextOp(ctx, bcq.ctx, "All")
	if err := bcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BlockCategory, *BlockCategoryQuery]()
	return withInterceptors[[]*BlockCategory](ctx, bcq, qr, bcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bcq *BlockCategoryQuery) AllX(ctx context.Context) []*BlockCategory {
	nodes, err := bcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlockCategory IDs.
func (bcq *BlockCategoryQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if bcq.ctx.Unique == nil && bcq.path != nil {
		bcq.Unique(true)
	}
	ctx = setContextOp(ctx, bcq.ctx, "IDs")
	if err = bcq.Select(blockcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bcq *BlockCategoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := bcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bcq *BlockCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bcq.ctx, "Count")
	if err := bcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bcq, querierCount[*BlockCategoryQuery](), bcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bcq *BlockCategoryQuery) CountX(ctx context.Context) int {
	count, err := bcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bcq *BlockCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bcq.ctx, "Exist")
	switch _, err := bcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bcq *BlockCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := bcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlockCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bcq *BlockCategoryQuery) Clone() *BlockCategoryQuery {
	if bcq == nil {
		return nil
	}
	return &BlockCategoryQuery{
		config:     bcq.config,
		ctx:        bcq.ctx.Clone(),
		order:      append([]blockcategory.OrderOption{}, bcq.order...),
		inters:     append([]Interceptor{}, bcq.inters...),
		predicates: append([]predicate.BlockCategory{}, bcq.predicates...),
		withBlocks: bcq.withBlocks.Clone(),
		withBot:    bcq.withBot.Clone(),
		// clone intermediate query.
		sql:  bcq.sql.Clone(),
		path: bcq.path,
	}
}

// WithBlocks tells the query-builder to eager-load the nodes that are connected to
// the "blocks" edge. The optional arguments are used to configure the query builder of the edge.
func (bcq *BlockCategoryQuery) WithBlocks(opts ...func(*BlockInfoQuery)) *BlockCategoryQuery {
	query := (&BlockInfoClient{config: bcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bcq.withBlocks = query
	return bcq
}

// WithBot tells the query-builder to eager-load the nodes that are connected to
// the "bot" edge. The optional arguments are used to configure the query builder of the edge.
func (bcq *BlockCategoryQuery) WithBot(opts ...func(*BotQuery)) *BlockCategoryQuery {
	query := (&BotClient{config: bcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bcq.withBot = query
	return bcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlockCategory.Query().
//		GroupBy(blockcategory.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bcq *BlockCategoryQuery) GroupBy(field string, fields ...string) *BlockCategoryGroupBy {
	bcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BlockCategoryGroupBy{build: bcq}
	grbuild.flds = &bcq.ctx.Fields
	grbuild.label = blockcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.BlockCategory.Query().
//		Select(blockcategory.FieldName).
//		Scan(ctx, &v)
func (bcq *BlockCategoryQuery) Select(fields ...string) *BlockCategorySelect {
	bcq.ctx.Fields = append(bcq.ctx.Fields, fields...)
	sbuild := &BlockCategorySelect{BlockCategoryQuery: bcq}
	sbuild.label = blockcategory.Label
	sbuild.flds, sbuild.scan = &bcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BlockCategorySelect configured with the given aggregations.
func (bcq *BlockCategoryQuery) Aggregate(fns ...AggregateFunc) *BlockCategorySelect {
	return bcq.Select().Aggregate(fns...)
}

func (bcq *BlockCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bcq); err != nil {
				return err
			}
		}
	}
	for _, f := range bcq.ctx.Fields {
		if !blockcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bcq.path != nil {
		prev, err := bcq.path(ctx)
		if err != nil {
			return err
		}
		bcq.sql = prev
	}
	return nil
}

func (bcq *BlockCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlockCategory, error) {
	var (
		nodes       = []*BlockCategory{}
		withFKs     = bcq.withFKs
		_spec       = bcq.querySpec()
		loadedTypes = [2]bool{
			bcq.withBlocks != nil,
			bcq.withBot != nil,
		}
	)
	if bcq.withBot != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, blockcategory.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BlockCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BlockCategory{config: bcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bcq.withBlocks; query != nil {
		if err := bcq.loadBlocks(ctx, query, nodes,
			func(n *BlockCategory) { n.Edges.Blocks = []*BlockInfo{} },
			func(n *BlockCategory, e *BlockInfo) { n.Edges.Blocks = append(n.Edges.Blocks, e) }); err != nil {
			return nil, err
		}
	}
	if query := bcq.withBot; query != nil {
		if err := bcq.loadBot(ctx, query, nodes, nil,
			func(n *BlockCategory, e *Bot) { n.Edges.Bot = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bcq *BlockCategoryQuery) loadBlocks(ctx context.Context, query *BlockInfoQuery, nodes []*BlockCategory, init func(*BlockCategory), assign func(*BlockCategory, *BlockInfo)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*BlockCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.BlockInfo(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(blockcategory.BlocksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.block_category_blocks
		if fk == nil {
			return fmt.Errorf(`foreign-key "block_category_blocks" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "block_category_blocks" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (bcq *BlockCategoryQuery) loadBot(ctx context.Context, query *BotQuery, nodes []*BlockCategory, init func(*BlockCategory), assign func(*BlockCategory, *Bot)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*BlockCategory)
	for i := range nodes {
		if nodes[i].bot_blocks == nil {
			continue
		}
		fk := *nodes[i].bot_blocks
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(bot.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bot_blocks" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bcq *BlockCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bcq.querySpec()
	_spec.Node.Columns = bcq.ctx.Fields
	if len(bcq.ctx.Fields) > 0 {
		_spec.Unique = bcq.ctx.Unique != nil && *bcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bcq.driver, _spec)
}

func (bcq *BlockCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(blockcategory.Table, blockcategory.Columns, sqlgraph.NewFieldSpec(blockcategory.FieldID, field.TypeUUID))
	_spec.From = bcq.sql
	if unique := bcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bcq.path != nil {
		_spec.Unique = true
	}
	if fields := bcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blockcategory.FieldID)
		for i := range fields {
			if fields[i] != blockcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bcq *BlockCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bcq.driver.Dialect())
	t1 := builder.Table(blockcategory.Table)
	columns := bcq.ctx.Fields
	if len(columns) == 0 {
		columns = blockcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bcq.sql != nil {
		selector = bcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bcq.ctx.Unique != nil && *bcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bcq.predicates {
		p(selector)
	}
	for _, p := range bcq.order {
		p(selector)
	}
	if offset := bcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BlockCategoryGroupBy is the group-by builder for BlockCategory entities.
type BlockCategoryGroupBy struct {
	selector
	build *BlockCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bcgb *BlockCategoryGroupBy) Aggregate(fns ...AggregateFunc) *BlockCategoryGroupBy {
	bcgb.fns = append(bcgb.fns, fns...)
	return bcgb
}

// Scan applies the selector query and scans the result into the given value.
func (bcgb *BlockCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bcgb.build.ctx, "GroupBy")
	if err := bcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockCategoryQuery, *BlockCategoryGroupBy](ctx, bcgb.build, bcgb, bcgb.build.inters, v)
}

func (bcgb *BlockCategoryGroupBy) sqlScan(ctx context.Context, root *BlockCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bcgb.fns))
	for _, fn := range bcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bcgb.flds)+len(bcgb.fns))
		for _, f := range *bcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BlockCategorySelect is the builder for selecting fields of BlockCategory entities.
type BlockCategorySelect struct {
	*BlockCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bcs *BlockCategorySelect) Aggregate(fns ...AggregateFunc) *BlockCategorySelect {
	bcs.fns = append(bcs.fns, fns...)
	return bcs
}

// Scan applies the selector query and scans the result into the given value.
func (bcs *BlockCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bcs.ctx, "Select")
	if err := bcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BlockCategoryQuery, *BlockCategorySelect](ctx, bcs.BlockCategoryQuery, bcs, bcs.inters, v)
}

func (bcs *BlockCategorySelect) sqlScan(ctx context.Context, root *BlockCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bcs.fns))
	for _, fn := range bcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
