// Code generated by ent, DO NOT EDIT.

package ent

import (
	"oliapi/ent/blockcategory"
	"oliapi/ent/blockinfo"
	"oliapi/ent/bot"
	"oliapi/ent/company"
	"oliapi/ent/role"
	"oliapi/ent/schema"
	"oliapi/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blockcategoryFields := schema.BlockCategory{}.Fields()
	_ = blockcategoryFields
	// blockcategoryDescCreatedAt is the schema descriptor for created_at field.
	blockcategoryDescCreatedAt := blockcategoryFields[2].Descriptor()
	// blockcategory.DefaultCreatedAt holds the default value on creation for the created_at field.
	blockcategory.DefaultCreatedAt = blockcategoryDescCreatedAt.Default.(func() time.Time)
	// blockcategoryDescUpdatedAt is the schema descriptor for updated_at field.
	blockcategoryDescUpdatedAt := blockcategoryFields[3].Descriptor()
	// blockcategory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blockcategory.DefaultUpdatedAt = blockcategoryDescUpdatedAt.Default.(func() time.Time)
	// blockcategoryDescID is the schema descriptor for id field.
	blockcategoryDescID := blockcategoryFields[0].Descriptor()
	// blockcategory.DefaultID holds the default value on creation for the id field.
	blockcategory.DefaultID = blockcategoryDescID.Default.(func() uuid.UUID)
	blockinfoFields := schema.BlockInfo{}.Fields()
	_ = blockinfoFields
	// blockinfoDescCreatedAt is the schema descriptor for created_at field.
	blockinfoDescCreatedAt := blockinfoFields[2].Descriptor()
	// blockinfo.DefaultCreatedAt holds the default value on creation for the created_at field.
	blockinfo.DefaultCreatedAt = blockinfoDescCreatedAt.Default.(func() time.Time)
	// blockinfoDescUpdatedAt is the schema descriptor for updated_at field.
	blockinfoDescUpdatedAt := blockinfoFields[3].Descriptor()
	// blockinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blockinfo.DefaultUpdatedAt = blockinfoDescUpdatedAt.Default.(func() time.Time)
	// blockinfoDescID is the schema descriptor for id field.
	blockinfoDescID := blockinfoFields[0].Descriptor()
	// blockinfo.DefaultID holds the default value on creation for the id field.
	blockinfo.DefaultID = blockinfoDescID.Default.(func() uuid.UUID)
	botFields := schema.Bot{}.Fields()
	_ = botFields
	// botDescCreatedAt is the schema descriptor for created_at field.
	botDescCreatedAt := botFields[4].Descriptor()
	// bot.DefaultCreatedAt holds the default value on creation for the created_at field.
	bot.DefaultCreatedAt = botDescCreatedAt.Default.(func() time.Time)
	// botDescUpdatedAt is the schema descriptor for updated_at field.
	botDescUpdatedAt := botFields[5].Descriptor()
	// bot.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bot.DefaultUpdatedAt = botDescUpdatedAt.Default.(func() time.Time)
	// botDescID is the schema descriptor for id field.
	botDescID := botFields[0].Descriptor()
	// bot.DefaultID holds the default value on creation for the id field.
	bot.DefaultID = botDescID.Default.(func() uuid.UUID)
	companyFields := schema.Company{}.Fields()
	_ = companyFields
	// companyDescCreatedAt is the schema descriptor for created_at field.
	companyDescCreatedAt := companyFields[4].Descriptor()
	// company.DefaultCreatedAt holds the default value on creation for the created_at field.
	company.DefaultCreatedAt = companyDescCreatedAt.Default.(func() time.Time)
	// companyDescUpdatedAt is the schema descriptor for updated_at field.
	companyDescUpdatedAt := companyFields[5].Descriptor()
	// company.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	company.DefaultUpdatedAt = companyDescUpdatedAt.Default.(func() time.Time)
	// companyDescID is the schema descriptor for id field.
	companyDescID := companyFields[0].Descriptor()
	// company.DefaultID holds the default value on creation for the id field.
	company.DefaultID = companyDescID.Default.(func() uuid.UUID)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
